import type { Metadata } from "next";
import { Inter, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { CursorBackgroundGradient } from "@/app/components/CursorBackgroundGradient";
import { Header } from "@/app/components/Header";

const inter = Inter({ subsets: ["latin"] });
export const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen bg-white">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
