import { Header } from "@/app/components/Header";
import { hindVadodara } from "@/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-white max-w-[100vw]">
      <body className={hindVadodara.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
